### ISSUE TITLE
Nuclearcraft Radiation Crashes Essentia Brazier

### ISSUE THREAD

**Issue by Keyedrin** [duely/brazier#1]
Placing a brazier in a world with Nuclearcraft Radiation enabled causes the game to crash. The related crash report is attached.

[crash-2019-07-11_20.31.02-server.txt](https://github.com/duely/brazier/files/3388199/crash-2019-07-11_20.31.02-server.txt)

**Comment by noobanidus** [comment]
Glad this was resolved, thanks!
